-- =============================================================================
-- 001_categories.sql — Store Categories (table + cover-image bucket + read query)
-- =============================================================================
--
-- Run this once in the Supabase SQL editor (or psql). It is idempotent — safe to
-- re-run on a database that already has a `categories` table.
--
-- Mirrors the upcoming_projects setup exactly:
--
--   upcoming_projects            categories
--   ------------------------     --------------------------
--   bucket  project-images       bucket  category-images        (public)
--   object  <project id>-cover   object  <category id>-cover
--   URL     <SUPABASE_URL>/storage/v1/object/public/<bucket>/<id>-cover
--
-- The backend (backend/server.js, GET /api/categories) reads the
-- `categories_with_image` view defined at the bottom of this file, which joins
-- storage.objects so the API knows whether a cover actually exists and when it
-- was last replaced (used for cache-busting).
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. Table
-- -----------------------------------------------------------------------------
create table if not exists public.categories (
    id          bigint generated by default as identity primary key,
    name        text        not null,
    url_slug    text        not null,
    is_active   boolean     not null default true,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

-- Columns the admin panel needs on top of the original six.
alter table public.categories add column if not exists description   text;
alter table public.categories add column if not exists product_count integer not null default 0;
alter table public.categories add column if not exists is_featured   boolean not null default false;
alter table public.categories add column if not exists parent_id     bigint;

comment on column public.categories.product_count is
    'Manually maintained until a products table exists; see the note at the bottom of this file.';


-- -----------------------------------------------------------------------------
-- 2. Make sure `id` auto-generates
--    A table created through the Supabase table editor without "Is Identity"
--    ticked will reject every insert coming from the API with a null-id error.
-- -----------------------------------------------------------------------------
do $$
declare
    v_is_identity text;
    v_default     text;
begin
    select is_identity, column_default
      into v_is_identity, v_default
      from information_schema.columns
     where table_schema = 'public'
       and table_name   = 'categories'
       and column_name  = 'id';

    if v_is_identity = 'NO' and v_default is null then
        alter table public.categories alter column id add generated by default as identity;

        -- Start the sequence above whatever rows are already in the table.
        perform setval(
            pg_get_serial_sequence('public.categories', 'id'),
            coalesce((select max(id) from public.categories), 0) + 1,
            false
        );
    end if;
end $$;


-- -----------------------------------------------------------------------------
-- 3. Backfill, then harden
-- -----------------------------------------------------------------------------

-- Any row that predates this migration and has no slug gets one from its name,
-- using the same rule the backend uses (lowercase, non-alphanumerics -> '-').
update public.categories
   set url_slug = regexp_replace(
                      regexp_replace(lower(btrim(name)), '[^a-z0-9]+', '-', 'g'),
                      '^-+|-+$', '', 'g'
                  )
 where url_slug is null
    or btrim(url_slug) = '';

alter table public.categories alter column url_slug  set not null;
alter table public.categories alter column is_active set not null;
alter table public.categories alter column is_active set default true;

-- One slug -> one category. The backend turns violations into a 409 with a
-- readable message instead of a 500.
create unique index if not exists categories_url_slug_key on public.categories (url_slug);
create index        if not exists categories_is_active_idx on public.categories (is_active);
create index        if not exists categories_parent_id_idx on public.categories (parent_id);

-- Sub-categories. Deleting a parent promotes its children to top level rather
-- than cascading the delete.
do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'categories_parent_id_fkey') then
        alter table public.categories
            add constraint categories_parent_id_fkey
            foreign key (parent_id) references public.categories (id) on delete set null;
    end if;

    if not exists (select 1 from pg_constraint where conname = 'categories_parent_not_self') then
        alter table public.categories
            add constraint categories_parent_not_self check (parent_id is distinct from id);
    end if;
end $$;


-- -----------------------------------------------------------------------------
-- 4. updated_at maintenance
--    The backend also sends updated_at on every write, so the column stays
--    correct even if this trigger is ever dropped.
-- -----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists categories_set_updated_at on public.categories;
create trigger categories_set_updated_at
    before update on public.categories
    for each row execute function public.set_updated_at();


-- -----------------------------------------------------------------------------
-- 5. Grants
--
--    REQUIRED — without this the API fails with:
--      code 42501, "permission denied for table categories"
--
--    That is exactly what the existing table does today. PostgREST connects as
--    anon / authenticated / service_role, and the service role's RLS *bypass*
--    does not include table privileges — those still have to be granted. The
--    enquiries/upcoming_projects tables already have them, this one does not.
-- -----------------------------------------------------------------------------
grant usage on schema public to anon, authenticated, service_role;

-- Backend (service role) does all the writing.
grant select, insert, update, delete on public.categories to service_role;

-- Storefront reads; still filtered by the RLS policy in section 6.
grant select on public.categories to anon, authenticated;

-- Inserts need the identity sequence too.
do $$
declare
    v_seq text := pg_get_serial_sequence('public.categories', 'id');
begin
    if v_seq is not null then
        execute format('grant usage, select on sequence %s to service_role', v_seq);
    end if;
end $$;


-- -----------------------------------------------------------------------------
-- 6. Row level security
--    The admin dashboard never touches this table directly — it goes through
--    the Express API with the service role key, which bypasses RLS. The policy
--    below only opens up what the public storefront is allowed to see.
-- -----------------------------------------------------------------------------
alter table public.categories enable row level security;

drop policy if exists "Public can read active categories" on public.categories;
create policy "Public can read active categories"
    on public.categories
    for select
    to anon, authenticated
    using (is_active = true);


-- -----------------------------------------------------------------------------
-- 7. Cover-image bucket
-- -----------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('category-images', 'category-images', true)
on conflict (id) do update set public = true;

-- Public read for the storefront + the admin table thumbnails.
drop policy if exists "Public can read category images" on storage.objects;
create policy "Public can read category images"
    on storage.objects
    for select
    to public
    using (bucket_id = 'category-images');

-- Writes are intentionally NOT opened to anon/authenticated: uploads only happen
-- through POST /api/categories, which runs on the service role key.


-- -----------------------------------------------------------------------------
-- 8. THE READ QUERY — categories joined to their cover image in the bucket
--
--     select * from public.categories_with_image order by name asc;
--
--    `image_path` is null when the admin has not uploaded a cover yet, so the
--    API can send image_url: null instead of a URL that 404s (which is what the
--    upcoming_projects route does today — it builds the URL blindly and lets the
--    browser fail). `image_updated_at` changes every time a cover is replaced and
--    is appended to the URL as ?v=… so a re-upload is visible immediately.
--
--    Full public URL, assembled by the backend:
--      <SUPABASE_URL>/storage/v1/object/public/category-images/<image_path>
-- -----------------------------------------------------------------------------
drop view if exists public.categories_with_image;

create view public.categories_with_image as
select
    c.id,
    c.name,
    c.url_slug,
    c.description,
    c.product_count,
    c.is_active,
    c.is_featured,
    c.parent_id,
    c.created_at,
    c.updated_at,
    o.name        as image_path,
    o.updated_at  as image_updated_at
from public.categories c
left join storage.objects o
       on o.bucket_id = 'category-images'
      and o.name      = c.id::text || '-cover';

-- Deliberately NOT granted to anon/authenticated. A plain view runs with its
-- owner's privileges, so the owner's RLS bypass would leak inactive categories
-- (and storage metadata) to the public. Only the backend's service role reads it.
revoke all on public.categories_with_image from anon, authenticated;
grant select on public.categories_with_image to service_role;


-- -----------------------------------------------------------------------------
-- 9. Seed (only if the table is empty — re-running this file will not duplicate)
-- -----------------------------------------------------------------------------
insert into public.categories (name, url_slug, description, product_count, is_active)
select * from (values
    ('Machinery',            'machinery', 'Framing and moulding production machinery.', 48,  true),
    ('Photo Frame Moldings', 'moldings',  'Profiles and moulding lengths.',             156, true),
    ('Hardware & Accessories','hardware', 'Fittings, clips, hangers and consumables.',  89,  true),
    ('Lubricants & Oils',    'oils',      'Machine oils, greases and cleaning agents.', 27,  false)
) as seed(name, url_slug, description, product_count, is_active)
where not exists (select 1 from public.categories);


-- =============================================================================
-- NOTE ON product_count  —  SUPERSEDED, see 006_derive_category_product_count.sql
-- =============================================================================
-- DONE. 002 created the products table and 006 carried out exactly what this note
-- describes: the manual column is dropped and the count is derived. The seed below
-- still writes product_count so that this file stays runnable on its own, against
-- a database where 006 has not been applied yet.
--
-- The original note, kept for the reasoning:
--
-- There is no products table in this database yet, so product_count is a plain
-- column the admin edits by hand. Once products exist with a category_id column,
-- replace it with a derived value and drop the manual field from the drawer:
--
--   alter table public.categories drop column product_count;
--
--   drop view if exists public.categories_with_image;
--   create view public.categories_with_image as
--   select c.*,
--          (select count(*) from public.products p where p.category_id = c.id) as product_count,
--          o.name       as image_path,
--          o.updated_at as image_updated_at
--     from public.categories c
--     left join storage.objects o
--            on o.bucket_id = 'category-images'
--           and o.name      = c.id::text || '-cover';
--
-- The API response shape does not change, so no frontend edits are needed.
-- =============================================================================
