-- =============================================================================
-- 004_product_images.sql — Grouped per-product image storage (up to 4, one main)
-- =============================================================================
--
-- Run after 003_product_flags.sql. Idempotent — safe to re-run.
--
-- THE PROBLEM THIS REPLACES
-- -------------------------
-- 002 gave every product a single cover stored as a flat object named
-- `<product id>-cover`, borrowed from the categories convention. That does not
-- stretch to four images: flat names like `7-cover`, `7-2`, `7-3` are not
-- grouped in any meaningful way, nothing records which one is the main image,
-- and listing a product's images means scanning the whole bucket by prefix.
--
-- `products.gallery_paths text[]` (the renamed original column) is NOT used by
-- this design — an array of paths cannot express ordering constraints, cannot be
-- indexed usefully, and has no way to guarantee exactly one main image. It stays
-- in place, unused, so nothing depends on it. Drop it whenever you like:
--
--     alter table public.products drop column gallery_paths;
--
--
-- THE SOLUTION
-- ------------
-- Two halves that mirror each other:
--
--   1. STORAGE  — one folder per product inside the existing bucket:
--
--          product-images/
--            ├── 7/1   ← product 7, slot 1
--            ├── 7/2
--            ├── 7/3
--            └── 12/1  ← product 12, slot 1
--
--      Every image for a product lives under a single prefix, so listing,
--      moving, or deleting a product's images is one prefix operation instead
--      of a bucket-wide search.
--
--   2. DATABASE — one row per image in `product_images`, grouped by product_id:
--
--          product_id | slot | is_main
--          -----------+------+--------
--                   7 |    1 | true
--                   7 |    2 | false
--                   7 |    3 | false
--
--      The row is the record of truth for which slots exist and which one is
--      main. The object name is always `<product_id>/<slot>`, so the two halves
--      never need to store the same string twice.
--
-- Slots are capped at 4 by a check constraint, so the database enforces the
-- limit the admin UI presents rather than trusting the form.
--
-- NOTE: deleting a product cascades its product_images rows, but Postgres cannot
-- reach into storage. DELETE /api/products/:id lists the `<id>/` prefix and
-- removes the objects itself.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. Table
-- -----------------------------------------------------------------------------
create table if not exists public.product_images (
    id          bigint generated by default as identity primary key,
    product_id  bigint      not null references public.products (id) on delete cascade,
    slot        smallint    not null,
    is_main     boolean     not null default false,
    created_at  timestamptz not null default now(),
    updated_at  timestamptz not null default now()
);

comment on table public.product_images is
    'One row per uploaded product image. The storage object is always product-images/<product_id>/<slot>.';


-- -----------------------------------------------------------------------------
-- 2. Constraints
--
--    The slot cap is the database's copy of the "4 images" rule. Without it a
--    bug in the form could write slot 9 and the admin UI would silently never
--    show that image again.
-- -----------------------------------------------------------------------------
do $$
begin
    if not exists (select 1 from pg_constraint where conname = 'product_images_slot_range') then
        alter table public.product_images
            add constraint product_images_slot_range check (slot between 1 and 4);
    end if;
end $$;

-- One image per slot per product.
create unique index if not exists product_images_product_slot_key
    on public.product_images (product_id, slot);

-- At most one main image per product. A partial unique index is what makes this
-- impossible to violate, rather than something the API has to remember.
create unique index if not exists product_images_one_main_key
    on public.product_images (product_id) where is_main;

create index if not exists product_images_product_id_idx
    on public.product_images (product_id);


-- -----------------------------------------------------------------------------
-- 3. Exactly one main, maintained by the database
--
--    Setting a new main clears the old one automatically. Without this, the API
--    would have to unset-then-set in two statements and a crash between them
--    would leave a product with no main image at all.
-- -----------------------------------------------------------------------------
create or replace function public.product_images_single_main()
returns trigger
language plpgsql
as $$
begin
    if new.is_main then
        update public.product_images
           set is_main = false
         where product_id = new.product_id
           and id        <> new.id
           and is_main;
    end if;
    return new;
end;
$$;

drop trigger if exists product_images_single_main on public.product_images;
create trigger product_images_single_main
    before insert or update on public.product_images
    for each row execute function public.product_images_single_main();

-- Reuses set_updated_at() from 001_categories.sql.
drop trigger if exists product_images_set_updated_at on public.product_images;
create trigger product_images_set_updated_at
    before update on public.product_images
    for each row execute function public.set_updated_at();


-- -----------------------------------------------------------------------------
-- 4. Grants
--    Same trap as every other table here: the service role's RLS bypass does not
--    include table privileges.
-- -----------------------------------------------------------------------------
grant select, insert, update, delete on public.product_images to service_role;
grant select on public.product_images to anon, authenticated;

do $$
declare
    v_seq text := pg_get_serial_sequence('public.product_images', 'id');
begin
    if v_seq is not null then
        execute format('grant usage, select on sequence %s to service_role', v_seq);
    end if;
end $$;


-- -----------------------------------------------------------------------------
-- 5. Row level security
--    The storefront may read images, but only for products it is allowed to see.
--    Without the products join, an inactive product's images would still be
--    listable by anyone holding the anon key.
-- -----------------------------------------------------------------------------
alter table public.product_images enable row level security;

drop policy if exists "Public can read images of active products" on public.product_images;
create policy "Public can read images of active products"
    on public.product_images
    for select
    to anon, authenticated
    using (
        exists (
            select 1 from public.products p
             where p.id = product_images.product_id
               and p.is_active = true
        )
    );


-- -----------------------------------------------------------------------------
-- 6. Storage
--    The bucket and its public-read policy already exist from 002. Folder paths
--    live inside the same bucket, so `bucket_id = 'product-images'` covers
--    `7/1` exactly as it covered `7-cover`. Nothing new is needed here — this
--    section exists so the convention is written down next to the table:
--
--        object name = <product_id>/<slot>        e.g.  7/3
--        public URL  = <SUPABASE_URL>/storage/v1/object/public/product-images/7/3
-- -----------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;


-- -----------------------------------------------------------------------------
-- 7. THE READ QUERY — products with their grouped images
--
--    `images` is a JSON array, already ordered by slot, carrying everything the
--    API needs to build URLs:
--
--      [{"slot":1,"is_main":true,"path":"7/1","updated_at":"2026-08-18T..."}, ...]
--
--    `updated_at` comes from the storage object when it exists, so replacing an
--    image changes the ?v= cache-buster on that image alone. It falls back to
--    the row's timestamp when the object is missing (a row whose upload failed),
--    which keeps the payload shape stable.
--
--    Aggregating here means one query returns every product with every image —
--    the alternative, calling storage.list() per product, is an N+1.
-- -----------------------------------------------------------------------------
drop view if exists public.products_with_image;

create view public.products_with_image as
select
    p.id,
    p.name,
    p.url_slug,
    p.description,
    p.price,
    p.category_id,
    p.asset_folder,
    p.is_active,
    p.is_featured,
    p.is_best_seller,
    p.is_new_arrival,
    p.created_at,
    p.updated_at,
    c.name as category_name,
    coalesce(img.images, '[]'::json) as images
from public.products p
left join public.categories c
       on c.id = p.category_id
left join lateral (
    select json_agg(
               json_build_object(
                   'slot',       pi.slot,
                   'is_main',    pi.is_main,
                   'path',       p.id::text || '/' || pi.slot::text,
                   'updated_at', coalesce(o.updated_at, pi.updated_at)
               )
               order by pi.slot
           ) as images
      from public.product_images pi
      left join storage.objects o
             on o.bucket_id = 'product-images'
            and o.name      = p.id::text || '/' || pi.slot::text
     where pi.product_id = p.id
) img on true;

-- Deliberately NOT granted to anon/authenticated. A plain view runs with its
-- owner's privileges, so the owner's RLS bypass would leak inactive products.
revoke all on public.products_with_image from anon, authenticated;
grant select on public.products_with_image to service_role;


-- -----------------------------------------------------------------------------
-- 8. Refresh PostgREST's schema cache immediately.
-- -----------------------------------------------------------------------------
notify pgrst, 'reload schema';


-- =============================================================================
-- VERIFY
-- =============================================================================
-- select
--     (select count(*) = 1 from information_schema.tables
--       where table_schema='public' and table_name='product_images')        as has_table,
--     (select count(*) = 1 from pg_indexes
--       where indexname='product_images_one_main_key')                      as has_one_main_index,
--     (select count(*) = 1 from pg_indexes
--       where indexname='product_images_product_slot_key')                  as has_slot_unique,
--     (select count(*) = 1 from pg_constraint
--       where conname='product_images_slot_range')                          as has_slot_cap,
--     (select relrowsecurity from pg_class
--       where oid='public.product_images'::regclass)                        as rls_on,
--     (select count(*) = 1 from pg_views
--       where viewname='products_with_image')                               as has_view;
--
-- Expected: true, true, true, true, true, true
--
-- Then confirm the shape the API consumes:
--   select id, name, images from public.products_with_image;
-- =============================================================================
