-- =============================================================================
-- 007_quote_form_type.sql — the "quote" form type the store's quote form posts as
-- =============================================================================
--
-- Run once in the Supabase SQL editor (or psql). Idempotent — safe to re-run.
--
-- WHY
-- ---
-- POST /api/submit-form resolves `form_type` against `form_types.type_name` with
-- an exact match and rejects the submission outright if there is no such row:
--
--     if (typeError || !typeData) throw new Error("Invalid form type submitted.");
--
-- `form_types` predates the migrations folder and was seeded by hand, so the
-- contact form's 'enquiry' row exists on the live database but nothing in this
-- repository says so, and nothing guarantees a 'quote' row on a fresh one. The
-- store's Request a Quote overlay (request-quote-module.js) posts
-- `form_type: 'quote'`, so without this row every quote request returns a 500
-- and the customer sees the overlay's failure banner.
--
-- WHY 'quote' AND NOT 'quotation'
-- -------------------------------
-- The admin dashboard sorts enquiries into its two tabs on a substring test —
-- `enquiries.js`:
--
--     if (typeName.includes('quote')) { ...quotations } else { ...technical }
--
-- so any name containing "quote" files correctly. 'quote' is the shortest thing
-- that satisfies it, and matches the literal the frontend sends.
--
-- WHAT IT DOES
-- ------------
-- Creates `form_types` only if it is somehow absent (a fresh database that has
-- never had the contact form pointed at it), then seeds 'enquiry' and 'quote'
-- if they are not already there. Existing rows are left exactly as they are —
-- the live table's ids are referenced by every enquiry already stored, so this
-- file must never rewrite them.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Table (no-op on the live database, which already has it)
-- -----------------------------------------------------------------------------
create table if not exists public.form_types (
    id         bigint generated by default as identity primary key,
    type_name  text not null
);

-- -----------------------------------------------------------------------------
-- 2. Seed
-- -----------------------------------------------------------------------------
-- `not exists` rather than `on conflict do nothing`: the live table is not known
-- to carry a unique index on type_name, and an ON CONFLICT clause naming a
-- constraint that does not exist is an error rather than a no-op.
--
-- Matched case-insensitively so a hand-seeded 'Quote' or 'Enquiry' is recognised
-- and not duplicated. The backend's own lookup is case-sensitive and exact, so
-- if yours is capitalised, either lowercase it here or change FORM_TYPE in
-- request-quote-module.js to match — the two have to agree.
insert into public.form_types (type_name)
select 'enquiry'
where not exists (
    select 1 from public.form_types where lower(type_name) = 'enquiry'
);

insert into public.form_types (type_name)
select 'quote'
where not exists (
    select 1 from public.form_types where lower(type_name) = 'quote'
);

-- -----------------------------------------------------------------------------
-- 3. Check
-- -----------------------------------------------------------------------------
-- Expect at least the two rows above. If 'quote' comes back capitalised, see the
-- note in section 2 before assuming the overlay will work.
select id, type_name from public.form_types order by id;
