-- =============================================================================
-- 009_quote_requests.sql — quote requests get their own tables
-- =============================================================================
--
-- Run once in the Supabase SQL editor (or psql). Idempotent — safe to re-run.
-- Run 008_revert_quote_form_type.sql first; the two are one change.
--
-- WHY A NEW TABLE AND NOT A COLUMN ON `enquiries`
-- -----------------------------------------------
-- The two forms collect genuinely different things:
--
--   Technical Support        Request a Quote
--   -----------------        ---------------
--   name                     business name        <- the customer IS a business
--   company (optional)       contact person
--   email                    email
--   phone                    phone
--   message (free text)      business address     <- quoting needs a ship-to
--                            product requests     <- REPEATING: n x (category, product)
--                            notes (optional)
--
-- The last one is what settles it. A quote carries a *list* — the overlay's
-- "+ Add Another Product" is unbounded — and a list does not fit in a column.
-- Filing quotes as enquiries meant flattening that list into
-- `enquirer_text_message` as prose, which is write-only data: you cannot count
-- how often a product is quoted, cannot filter quotes by category, cannot join
-- to `products`, and the dashboard can only echo the blob back under a heading
-- that says "Issue".
--
-- So: one header row per request, one child row per requested product.
--
-- WHY THE ITEMS SNAPSHOT NAMES AND PRICES
-- ---------------------------------------
-- `category_id` / `product_id` are recorded as plain bigints with NO foreign key
-- to `products` / `categories`, and each item also stores the name and price as
-- they read at submission time. A quote is a historical record of what a
-- customer asked for on a given day. Products get renamed, repriced,
-- deactivated and deleted; a real FK would either block those deletes or cascade
-- them into the quote and silently rewrite history. The ids are still there for
-- joining when the product does still exist — they are just not a constraint.
--
-- The one FK that IS enforced is items -> quote_requests, because an item with
-- no header is meaningless. It also gives PostgREST the relationship it needs to
-- serve `select=*,quote_request_items(*)` as a single embedded read, which is
-- what GET /api/quote-requests uses.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Header — one row per submitted quote request
-- -----------------------------------------------------------------------------
-- `phone` is text, deliberately. `enquiries.enquirer_phone_number` is int8, which
-- drops leading zeros and cannot hold a "+" country code or spacing — flagged as
-- a TODO in server.js. This table does not repeat that mistake.
--
-- `status` reuses the exact three values the dashboard badges, drawer dropdown
-- and row menu already render for enquiries. Same vocabulary, so the Quotations
-- tab and the Technical Support tab stay one product.
create table if not exists public.quote_requests (
    id               bigint generated by default as identity primary key,
    business_name    text        not null,
    contact_name     text        not null,
    email            text        not null,
    phone            text,
    business_address text        not null,
    notes            text,
    status           text        not null default 'Open',
    created_at       timestamptz not null default now(),
    updated_at       timestamptz not null default now()
);

do $$
begin
    if not exists (
        select 1 from pg_constraint where conname = 'quote_requests_status_check'
    ) then
        alter table public.quote_requests
            add constraint quote_requests_status_check
            check (status in ('Open', 'In Progress', 'Resolved'));
    end if;
end $$;

-- -----------------------------------------------------------------------------
-- 2. Items — one row per requested product
-- -----------------------------------------------------------------------------
-- `position` is the order the customer built them in, so the dashboard can list
-- "Product Request #1, #2, #3" the way the overlay numbered them. Unique per
-- header so two items can never claim the same slot.
create table if not exists public.quote_request_items (
    id               bigint generated by default as identity primary key,
    quote_request_id bigint  not null references public.quote_requests (id) on delete cascade,
    position         integer not null,
    category_id      bigint,
    category_name    text    not null,
    product_id       bigint,
    product_name     text    not null,
    product_price    numeric,
    created_at       timestamptz not null default now(),
    constraint quote_request_items_position_unique unique (quote_request_id, position)
);

-- -----------------------------------------------------------------------------
-- 3. Indexes
-- -----------------------------------------------------------------------------
-- The dashboard lists newest first and always fetches the whole table; the
-- product/category indexes are for the reporting this table now makes possible
-- (how many quotes mentioned this product this quarter).
create index if not exists quote_requests_created_at_idx
    on public.quote_requests (created_at desc);

create index if not exists quote_requests_status_idx
    on public.quote_requests (status);

create index if not exists quote_request_items_request_idx
    on public.quote_request_items (quote_request_id, position);

create index if not exists quote_request_items_product_idx
    on public.quote_request_items (product_id);

create index if not exists quote_request_items_category_idx
    on public.quote_request_items (category_id);

-- -----------------------------------------------------------------------------
-- 4. updated_at maintenance
--    public.set_updated_at() already exists from 001_categories.sql; recreated
--    here with `or replace` so this file also stands alone on a fresh database.
-- -----------------------------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = now();
    return new;
end $$;

drop trigger if exists quote_requests_set_updated_at on public.quote_requests;
create trigger quote_requests_set_updated_at
    before update on public.quote_requests
    for each row execute function public.set_updated_at();

-- -----------------------------------------------------------------------------
-- 5. Grants
--    REQUIRED. PostgREST connects as anon / authenticated / service_role, and
--    the service role RLS *bypass* does not include table privileges — those
--    still have to be granted. Without this the API fails with
--    code 42501, "permission denied for table quote_requests".
-- -----------------------------------------------------------------------------
grant usage on schema public to anon, authenticated, service_role;

-- The Express API does every read and write on these tables. Nothing else does
-- — note there is no `grant select ... to anon` here, unlike categories and
-- products. See section 6.
grant select, insert, update, delete on public.quote_requests      to service_role;
grant select, insert, update, delete on public.quote_request_items to service_role;

-- Inserts need the identity sequences too.
do $$
declare
    v_seq text;
begin
    v_seq := pg_get_serial_sequence('public.quote_requests', 'id');
    if v_seq is not null then
        execute format('grant usage, select on sequence %s to service_role', v_seq);
    end if;

    v_seq := pg_get_serial_sequence('public.quote_request_items', 'id');
    if v_seq is not null then
        execute format('grant usage, select on sequence %s to service_role', v_seq);
    end if;
end $$;

-- -----------------------------------------------------------------------------
-- 6. Row level security — closed
-- -----------------------------------------------------------------------------
-- RLS on with NO policies means: nobody reaches these tables except the service
-- role, which bypasses RLS. That is the whole access model. The public
-- storefront only ever writes here, and it writes through POST
-- /api/quote-requests, not through PostgREST.
--
-- This is a deliberate difference from `enquiries`, which the admin dashboard
-- subscribes to directly from the browser with the anon key so its Technical
-- Support tab updates live. Realtime delivery is filtered by RLS, so giving the
-- Quotations tab the same live updates would mean granting anon SELECT on these
-- tables — publishing every name, email, phone and business address a customer
-- has given us to anyone who opens devtools. Quotations refetches on open.
--
-- If you decide the live updates are worth it, the opt-in is the commented block
-- below. Do not enable it without first moving the admin key server-side (see
-- the "Exposed admin secret" note in CLAUDE.md) — the two problems compound.
--
--   alter publication supabase_realtime add table public.quote_requests;
--   grant select on public.quote_requests to anon;
--   create policy "Anon can read quote requests"
--       on public.quote_requests for select to anon using (true);
--
alter table public.quote_requests      enable row level security;
alter table public.quote_request_items enable row level security;

-- -----------------------------------------------------------------------------
-- 7. Check
-- -----------------------------------------------------------------------------
-- Expect both tables with the columns above, and zero rows on a first run.
select
    (select count(*) from public.quote_requests)      as quote_requests,
    (select count(*) from public.quote_request_items) as quote_request_items;
